/* Automatically generated by wasm2c */
#ifndef QGIF_GENERATED_H_GENERATED_
#define QGIF_GENERATED_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_a;

typedef struct w2c_qgif {
  struct w2c_a* w2c_a_instance;
  u32 w2c_g0;
  wasm_rt_memory_t w2c_i;
  wasm_rt_funcref_table_t w2c_T0;
} w2c_qgif;

void wasm2c_qgif_instantiate(w2c_qgif*, struct w2c_a*);
void wasm2c_qgif_free(w2c_qgif*);
wasm_rt_func_type_t wasm2c_qgif_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'a' 'a' */
u32 w2c_a_a(struct w2c_a*, u32);

/* import: 'a' 'b' */
u32 w2c_a_b(struct w2c_a*, u32, u32, u32, u32);

/* import: 'a' 'c' */
u32 w2c_a_c(struct w2c_a*, u32, u32, u32);

/* import: 'a' 'd' */
u32 w2c_a_d(struct w2c_a*, u32);

/* import: 'a' 'e' */
u32 w2c_a_e(struct w2c_a*, u32, u64, u32, u32);

/* import: 'a' 'f' */
u32 w2c_a_f(struct w2c_a*, u32, u32, u32, u32);

/* import: 'a' 'g' */
u32 w2c_a_g(struct w2c_a*, u32, u32, u32);

/* import: 'a' 'h' */
u32 w2c_a_h(struct w2c_a*, u32, u32, u32, u32);

/* export: 'i' */
wasm_rt_memory_t* w2c_qgif_i(w2c_qgif* instance);

/* export: 'j' */
void w2c_qgif_j(w2c_qgif*);

/* export: 'k' */
void w2c_qgif_k(w2c_qgif*, u32);

/* export: 'l' */
u32 w2c_qgif_l(w2c_qgif*, u32);

/* export: 'm' */
u32 w2c_qgif_m(w2c_qgif*, u32, u32, u32, u32);

/* export: 'n' */
void w2c_qgif_n(w2c_qgif*, u32);

/* export: 'o' */
u32 w2c_qgif_o(w2c_qgif*, u32);

/* export: 'p' */
u32 w2c_qgif_p(w2c_qgif*);

#ifdef __cplusplus
}
#endif

#endif  /* QGIF_GENERATED_H_GENERATED_ */
